// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNCYk8ek3PRKUF9nkPjS7zsN0GyvR6YNc',
    appId: '1:530056062653:android:b4cfb38f9b2459528539d4',
    messagingSenderId: '530056062653',
    projectId: 'petpalace-b5aa9',
    storageBucket: 'petpalace-b5aa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmzLEWA-GzdQIdDCsYQ_TGq7linyqQMco',
    appId: '1:530056062653:ios:e6639c4523ed19428539d4',
    messagingSenderId: '530056062653',
    projectId: 'petpalace-b5aa9',
    storageBucket: 'petpalace-b5aa9.firebasestorage.app',
    iosBundleId: 'com.example.petpalace',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoMCtQZxQgjR0yQl7_CXcoDZzIV1JC0lU',
    appId: '1:530056062653:web:03596a065f5361ff8539d4',
    messagingSenderId: '530056062653',
    projectId: 'petpalace-b5aa9',
    authDomain: 'petpalace-b5aa9.firebaseapp.com',
    storageBucket: 'petpalace-b5aa9.firebasestorage.app',
    measurementId: 'G-5155TGN20V',
  );

}